---
resource_types:
  - name: artifactory-resource
    type: docker-image
    source:
      repository: pivotalservices/artifactory-resource
      tag: latest

  - name: maven-resource
    type: docker-image
    source:
      repository: nulldriver/maven-resource
      tag: latest

  - name: ansible
    type: docker-image
    source:
      repository: platformengineering/concourse-ansible-resource
      tag: latest

resources:
  - name: source_code
    type: git
    source:
      uri: {{auth_crewdock_repo}}
      branch: {{auth_crewdock_branch}}
      private_key: {{server_ssh_private_key}}
      skip_ssl_verification: true

jobs:
  - name: build
    serial: true
    public: true
    plan:
      - get: source_code
        trigger: true
      - task: test_app
        privileged: true
        file: source_code/ci/01-build/maven.yaml
        input_mapping:
          source_code: source_code


...