---
resources:
  - name: source_code
    type: git
    source:
      uri: {{test_container_repo}}
      branch: {{test_container_branch}}
      private_key: {{server_ssh_private_key}}
      skip_ssl_verification: true

jobs:
  - name: integration-tests
    serial: true
    public: true
    plan:
      - get: source_code
        trigger: true
      - task: test_app
        privileged: true
        file: source_code/ci/01-build/maven.yaml
        input_mapping:
          source_code: source_code


...